name: docker-php-builder

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  build-docker-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u tackleza --password-stdin

      - name: Build & Push PHP Docker Images
        run: |
          for dir in */; do
            if [[ -f "$dir/build.sh" && -f "$dir/push.sh" ]]; then
              echo "Building PHP in $dir"
              chmod +x "$dir/build.sh" "$dir/push.sh"
              (cd "$dir" && ./build.sh && ./push.sh)
            fi
          done
